SELECT * FROM PERFIL PER INNER JOIN CANDIDDATO CAN ON 
PER.CODIGO= CAN.CODIGO INNER JOIN EVALUACIONES EV ON 
CAN.CODIGO = EV.CODIGO INNER JOIN CASTING CAS ON
EV.CODIGO = CAS.CODIGO WHERE CODIGO= 1;




CODIGO_CONDUCTOR INT(10),FOREIGN KEY (CODIGO_CONDUCTOR)  REFERENCES  CONDUCTOR (CODIGO_CONDUCTOR), CODIGO_CAMION INT(10), FOREIGN KEY (CODIGO_CAMION)
                         REFERENCES CAMION (CODIGO_CAMION), CODIGO_PROVEEDOR INT(10), 
                         FOREIGN KEY (CODIGO_PROVEEDOR) REFERENCES PROVEEDOR (CODIGO_PROVEEDOR));






CREATE TABLE DET_ENTRADAS(CODIGO_DET_ENTRADA INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT, CANTIDAD INT(100), )

CREATE TABLE PRODUCTO(CODIGO_PRODUCTO INT (10) NOT NULL PRIMARY KEY AUTO_INCREMENT,  DESCRIPCION VARCHAR(100),
 CODIGO_CATEGORIA INT(10), FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CATEGORIA (CODIGO_CATEGORIA));

 CREATE TABLE DET_ENTRADAS(CODIGO_DET_ENTRADA INT (10) NOT NULL PRIMARY AUTO_INCREMENT, CANTIDAD INT (100), CODIGO_PRODUCTO INT(10),FOREIGN KEY (CODIGO_PRODUCTO)  REFERENCES  PRODUCTO (CODIGO_PRODUCTO), CODIGO_CATEGORIA INT(10), FOREIGN KEY (CODIGO_CATEGORIA)
                         REFERENCES CATEGORIA (CODIGO_CATEGORIA));

                         CREATE TABLE DET_ENTRADAS(CODIGO_DET_ENTRADA INT (10) NOT NULL PRIMARY KEY AUTO_INCREMENT, CANTIDAD INT (100), CODIGO_PRODUCTO INT(10),FOREIGN KEY (CODIGO_PRODUCTO)  REFERENCES  PRODUCTO (CODIGO_PRODUCTO), CODIGO_CATEGORIA INT(10), FOREIGN KEY (CODIGO_CATEGORIA)
                         REFERENCES CATEGORIA (CODIGO_CATEGORIA));

                         ALTER TABLE DET_ENTRADAS ADD(CODIGO_ENC_ENTRADA INT(10),FOREIGN KEY (CODIGO_ENC_ENTRADA)  REFERENCES  ENC_ENTRADAS (CODIGO_ENC_ENTRADA));

                         CREATE TABLE INVENTARIO( CODIGO_INVENTARIO INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT, DESCRIPCION VARCHAR(100), DISPONIBLE BOOLEAN, CUARENTENA VARCHAR(100),CODIGO_PRODUCTO INT(10),FOREIGN KEY (CODIGO_PRODUCTO)  REFERENCES  PRODUCTO (CODIGO_PRODUCTO));
                         CREATE TABLE TIPO_MOVIMIENTO(CODIGO_TIPO_MOVIMIENTO INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT, DESCRIPCION VARCHAR(100));

                         CREATE TABLE ENC_SALIDAS(CODIGO_ENC_SALIDA INT (10) NOT NULL PRIMARY KEY AUTO_INCREMENT, FECHA_SALIDA DATE, CODIGO_TIPO_MOVIMIENTO INT(10),FOREIGN KEY (CODIGO_TIPO_MOVIMIENTO)  REFERENCES  TIPO_MOVIMIENTO (CODIGO_TIPO_MOVIMIENTO));

                         CREATE TABLE DET_SALIDAS(CODIGO_DET_SALIDA INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT, CANTIDAD INT(100), CODIGO_PRODUCTO INT(10),FOREIGN KEY (CODIGO_PRODUCTO )  REFERENCES  PRODUCTO (CODIGO_PRODUCTO ), CODIGO_ENC_SALIDA INT(10), FOREIGN KEY (CODIGO_ENC_SALIDA)  REFERENCES ENC_SALIDAS (CODIGO_ENC_SALIDA) );